# Generated by Django 5.0.1 on 2025-03-25 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag de Projeto',
                'verbose_name_plural': 'Tags de Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao_curta', models.CharField(help_text='Descrição curta para exibição em cards', max_length=250)),
                ('descricao', models.TextField(help_text='Descrição completa do projeto')),
                ('imagem', models.ImageField(help_text='Imagem principal do projeto', upload_to='projetos/')),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em Andamento'), ('planejado', 'Planejado'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('link_github', models.URLField(blank=True, help_text='Link para repositório no GitHub', null=True)),
                ('link_video', models.URLField(blank=True, help_text='Link para vídeo do projeto', null=True)),
                ('link_documentacao', models.URLField(blank=True, help_text='Link para documentação', null=True)),
                ('mostrar_na_home', models.BooleanField(default=False, help_text='Se marcado, o projeto será exibido na página inicial')),
                ('publicado', models.BooleanField(default=True, help_text='Se marcado, o projeto estará visível no site')),
                ('destaque', models.BooleanField(default=False, help_text='Se marcado, receberá destaque visual')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('participantes', models.ManyToManyField(blank=True, related_name='projetos_participante', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='projetos', to='projetos.projetotag')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='projetos/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens dos Projetos',
                'ordering': ['ordem'],
            },
        ),
    ]
