# Generated by Django 5.0.1 on 2025-05-08 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('aprovado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Destacar este comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_projeto', to=settings.AUTH_USER_MODEL)),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='projetos.comentarioprojeto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Comentário do Projeto',
                'verbose_name_plural': 'Comentários dos Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
