# Generated by Django 5.0.1 on 2025-05-17 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_todotask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='visivel_para',
            field=models.ManyToManyField(blank=True, related_name='tarefas_visiveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjetoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_criados', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='grupos_projeto', to=settings.AUTH_USER_MODEL)),
                ('projetos', models.ManyToManyField(blank=True, related_name='grupos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Grupo de Projeto',
                'verbose_name_plural': 'Grupos de Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='todotask',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='projetos.projetogrupo'),
        ),
    ]
