# Generated by Django 5.0.1 on 2025-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canva', '0002_kanbancard_notas_kanbancard_progresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='visivel',
            field=models.BooleanField(default=True, help_text='Se marcado, o card será visível no quadro'),
        ),
    ]
