# Generated by Django 5.0.1 on 2025-05-03 19:12

import django.db.models.deletion
import repositorio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone FontAwesome (ex: fa-file-pdf)', max_length=50, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Recurso',
                'verbose_name_plural': 'Categorias de Recursos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('resource_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('code', 'Código'), ('text', 'Texto'), ('link', 'Link'), ('other', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('members', 'Apenas membros'), ('team', 'Apenas equipe interna')], default='members', max_length=20, verbose_name='Visibilidade')),
                ('file', models.FileField(blank=True, null=True, upload_to=repositorio.models.resource_file_path, verbose_name='Arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de arquivo')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo de texto')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='URL externa')),
                ('featured', models.BooleanField(default=False, help_text='Se marcado, este recurso será destacado na página do projeto', verbose_name='Destacado')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=200, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projetos.projeto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='repositorio.resourcecategory')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='repositorio.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
    ]
