# Generated by Django 5.0.1 on 2025-05-03 20:40

import django.db.models.deletion
import repositorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_type',
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Se em branco, será usado o nome do arquivo', max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to=repositorio.models.resource_file_path, verbose_name='Arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de arquivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='repositorio.resource')),
            ],
            options={
                'verbose_name': 'Arquivo de Recurso',
                'verbose_name_plural': 'Arquivos de Recursos',
                'ordering': ['upload_date'],
            },
        ),
    ]
