# Generated by Django 5.0.1 on 2025-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controle_ar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição exibida junto da imagem.', null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='link',
            field=models.CharField(blank=True, help_text='Link para tornar a imagem clicável.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, help_text='Título da imagem.', max_length=255, null=True),
        ),
    ]
