# Generated by Django 5.0.1 on 2025-05-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controle_ar', '0003_ar_condicionado_comando_ar_logoperacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_condicionado',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP do ESP32 (preenchido automaticamente)', null=True),
        ),
    ]
