# Generated by Django 5.0.1 on 2025-03-18 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_membro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(help_text='Nome do ícone FontAwesome (ex: fa-print)', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='servicos/')),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, help_text='Preço base ou mínimo', max_digits=10, null=True)),
                ('preco_adicional', models.TextField(blank=True, help_text='Explicação sobre custos adicionais ou variáveis')),
                ('tempo_estimado', models.CharField(blank=True, help_text="Ex: '2-3 dias', '1 semana', etc.", max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Serviço em destaque na página inicial')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='options.categoriaservico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoExemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='exemplos_servicos/')),
                ('data', models.DateField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplos', to='options.servico')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('descricao_projeto', models.TextField(help_text='Descreva seu projeto ou necessidade em detalhes')),
                ('arquivo_referencia', models.FileField(blank=True, help_text='Arquivo de referência ou modelo', null=True, upload_to='orcamentos/')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('respondido', 'Orçamento Enviado'), ('aprovado', 'Aprovado pelo Cliente'), ('recusado', 'Recusado pelo Cliente'), ('concluido', 'Serviço Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('valor_orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes_admin', models.TextField(blank=True, help_text='Observações internas (visíveis apenas para staff)')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.servico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamentos',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
