# Generated by Django 5.0.1 on 2025-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='noticias', to='options.hashtag'),
        ),
    ]
