# Generated by Django 5.0.1 on 2025-03-23 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_hashtag_noticia_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='preco_adicional',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='preco_base',
        ),
        migrations.CreateModel(
            name='SolicitacaoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('descricao_projeto', models.TextField(help_text='Descreva seu interesse ou projeto em detalhes')),
                ('arquivo_referencia', models.FileField(blank=True, help_text='Arquivo de referência ou modelo', null=True, upload_to='interesses/')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('respondido', 'Respondido'), ('concluido', 'Contato Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes_admin', models.TextField(blank=True, help_text='Observações internas (visíveis apenas para staff)')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.servico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Interesse',
                'verbose_name_plural': 'Solicitações de Interesse',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.DeleteModel(
            name='SolicitacaoOrcamento',
        ),
    ]
