# Generated by Django 5.0.1 on 2025-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_remove_servico_preco_adicional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descrição_do_material',
            new_name='descricao_do_material',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Nome_do_meterial',
            new_name='nome_do_material',
        ),
        migrations.AddField(
            model_name='material',
            name='ano_aquisicao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fabricante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='link_fabricante',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='outras_denominacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='parametros',
            field=models.TextField(blank=True, help_text='Potência, Capacidade, Área de impressão...', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='equipamentos_responsavel', to='options.membro'),
        ),
        migrations.AddField(
            model_name='material',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=10),
        ),
    ]
