# Generated by Django 5.0.1 on 2025-05-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0008_servico_aplicacoes_servico_como_utilizar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='aplicacoes',
            field=models.TextField(blank=True, help_text='Aplicações possíveis para este serviço (uma por linha)', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='como_utilizar',
            field=models.TextField(blank=True, help_text='Passos de como utilizar este serviço (um por linha)', null=True),
        ),
    ]
