# Generated by Django 6.0.3 on 2026-03-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_alter_servico_aplicacoes_alter_servico_como_utilizar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='noticias/galeria/')),
                ('legenda', models.CharField(blank=True, help_text='Legenda opcional da foto', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='options.noticia', verbose_name='Notícia')),
            ],
            options={
                'verbose_name': 'Foto da Notícia',
                'verbose_name_plural': 'Fotos das Notícias',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
