# Generated by Django 6.0.3 on 2026-03-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0005_projetomarco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icone', models.CharField(default='fa-chalkboard-teacher', help_text='Ícone FontAwesome (ex: fa-print)', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Curso',
                'verbose_name_plural': 'Categorias de Cursos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao_curta', models.CharField(help_text='Resumo exibido nos cards', max_length=300)),
                ('descricao', models.TextField(help_text='Conteúdo completo do curso')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, help_text='Em horas', null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vagas', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para vagas ilimitadas', null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('publicado', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('mostrar_na_home', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos.categoriacurso')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_criados', to=settings.AUTH_USER_MODEL)),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_ministrados', to=settings.AUTH_USER_MODEL)),
                ('projetos_relacionados', models.ManyToManyField(blank=True, help_text='Projetos do FabLab desenvolvidos neste curso ou relacionados a ele', related_name='cursos_relacionados', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
