# Generated by Django 5.0.1 on 2025-05-17 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0004_todotask_visivel_para_alter_todotask_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProjetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(help_text='Descrição do grupo de projetos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_gestao_criados', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='grupos_projetos', to=settings.AUTH_USER_MODEL)),
                ('projetos', models.ManyToManyField(blank=True, related_name='grupos_gestao', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Grupo de Projetos',
                'verbose_name_plural': 'Grupos de Projetos',
                'ordering': ['nome'],
            },
        ),
    ]
