# Generated by Django 5.0.1 on 2025-03-24 02:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('m²', 'Metro Quadrado')], default='un', max_length=2)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='inventario/itens/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='inventario.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='inventario.fornecedor')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventario.item')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
    ]
