# Generated by Django 6.0.3 on 2026-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_item_fornecedor_remove_movimentacao_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
