# Generated by Django 4.2.30 on 2026-05-27 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(help_text='Email do titular no momento da solicitação — mantido para auditoria.', max_length=254)),
                ('tipo', models.CharField(choices=[('exclusao', 'Exclusão de dados'), ('portabilidade', 'Portabilidade de dados'), ('acesso', 'Acesso aos dados'), ('correcao', 'Correção de dados'), ('oposicao', 'Oposição ao tratamento')], default='exclusao', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Referência preservada mesmo após anonimização do usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação LGPD',
                'verbose_name_plural': 'Solicitações LGPD',
                'ordering': ['-solicitado_em'],
            },
        ),
    ]
