# Generated by Django 5.0.1 on 2025-05-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_acesso', models.BooleanField(default=False)),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso_gestao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à Gestão',
                'verbose_name_plural': 'Acessos à Gestão',
            },
        ),
    ]
