# Generated by Django 5.0.1 on 2025-05-15 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Nome da configuração (código)', max_length=100, unique=True)),
                ('nome', models.CharField(help_text='Nome amigável da configuração', max_length=255)),
                ('valor', models.TextField(blank=True, help_text='Valor da configuração', null=True)),
                ('valor_padrao', models.TextField(blank=True, help_text='Valor padrão da configuração', null=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano'), ('email', 'Email'), ('url', 'URL'), ('cor', 'Cor'), ('data', 'Data'), ('hora', 'Hora'), ('arquivo', 'Arquivo'), ('json', 'JSON'), ('senha', 'Senha')], default='texto', help_text='Tipo de dado da configuração', max_length=20)),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('email', 'Email e Notificações'), ('acesso', 'Controle de Acesso'), ('visual', 'Aparência'), ('integracoes', 'Integrações'), ('armazenamento', 'Armazenamento'), ('logs', 'Logs e Monitoramento'), ('agendamento', 'Agendamento'), ('projetos', 'Projetos'), ('inventario', 'Inventário'), ('avancado', 'Configurações Avançadas')], default='geral', help_text='Categoria da configuração', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('restrito', models.BooleanField(default=False, help_text='Se apenas superusuários podem modificar esta configuração')),
                ('opcoes', models.JSONField(blank=True, help_text='Opções possíveis para seleção (para configurações com opções limitadas)', null=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
