# Generated by Django 5.0.1 on 2025-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('geral', 'Configurações Gerais'), ('email', 'Email e Notificações'), ('laboratorio', 'Configurações do Laboratório'), ('sistema', 'Sistema'), ('acesso', 'Controle de Acesso')], default='geral', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
    ]
